In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
# 데이터셋의 목록 읽어오기
file_list = os.listdir("./Dataset")
file_list

['a.npy']

In [3]:
# 파일 확장자 빼고 제스처 이름만 저장
actions = []
for i in range(len(file_list)) :
    actions.append(file_list[i][:-4])

actions

['a']

In [4]:
# 각 축을 기준으로 회전변환할 각도 Rotation Degree

## x축 기준 회전각 : pitch
RDx = np.deg2rad([5,10,20,30, 355,350,340,330])
## y축 기준 회전각 : yaw
RDy = np.deg2rad([5,10,20,30,40, 355,350,340,330,320])
## z축 기준 회전각 : roll
RDz = np.deg2rad([20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340])

In [5]:
RDx

array([0.08726646, 0.17453293, 0.34906585, 0.52359878, 6.19591884,
       6.10865238, 5.93411946, 5.75958653])

In [6]:
# 회전변환 행렬
def Rx(theta) :
    return np.array([ [1, 0, 0], 
                    [0, np.cos(theta), -np.sin(theta)], 
                    [0, np.sin(theta), np.cos(theta)]])
def Ry(theta) :
    return np.array([[np.cos(theta), 0, np.sin(theta)], 
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
def Rz(theta) :
    return np.array([[np.cos(theta), -np.sin(theta), 0], 
                    [np.sin(theta), np.cos(theta), 0], 
                    [0, 0, 1]])

In [7]:
loaded = np.load(f'./Dataset/{actions[i]}.npy')

In [8]:
len(loaded)

17

In [9]:
loaded[0][0]

array([7.13322282e-01, 8.22355270e-01, 6.18397848e-08])

In [10]:
np.dot(loaded[0][0], Rx(np.deg2rad(90)))

array([ 7.13322282e-01,  6.18397849e-08, -8.22355270e-01])

In [11]:
loaded[0][0] @ Rz(np.deg2rad(90)) @ Ry(np.deg2rad(90)) @ Rx(np.deg2rad(90))

array([-6.18397848e-08,  8.22355270e-01,  7.13322282e-01])

In [ ]:
# 각 제스처 좌표데이터별로
for i, gest in enumerate(actions):
    loaded = np.load(f'./Dataset/{actions[i]}.npy')
    
    # 회전변환
    gestCoord = []
    for rdz in RDz :
        for rdy in RDy :
            for rdx in RDx :
                
                for i in range(len(loaded)) :
                    frame = []
                    for j in range(21) :
                        frame.append( loaded[i][j] @ Rz(rdz) @ Ry(rdy) @ Rx(rdx) )
                        
                gestCoord.append((frame))

In [ ]:
gestCoord

In [ ]:
a = np.array(gestCoord)
a.shape , a